name: py_learn
description: Python offline tutorial app.

publish_to: 'none' 
version: 1.0.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_snake_navigationbar: ^0.5.0
  animations: ^2.0.0
  rich_code_editor: ^1.0.5
  url_launcher: ^6.0.7
  share: ^2.0.4
  link_text: ^0.2.0
  flutter_highlight: ^0.7.0
  cupertino_icons: ^1.0.2

flutter_app_name:
  name: "Py Learn"

flutter_native_splash:
  color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  chaquopy: ^0.0.11

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   

  
  fonts:
     - family: gots
       fonts:
         - asset: assets/fonts/gots.ttf
     - family: cb
       fonts:
         - asset: assets/fonts/cantate.ttf
     
  
